<?php
return [
	'USER_MAXIMUM_CARDS' => '5', // 用户可登记的银行卡的最大数量
	'MARKET_TRANSCATION_TAX_RATE' => '0.05', // 巢在市场交易完成时收取的税率
	'MONEY_MARKET_TO_ACTIVE_TAX_RATE' => '0.05', // 用户钱包中市场金额转为活动金额税率
	'EGG_VAL' => '7', // 一个蛋对应的美元额度
	'CONTRACT_PROFITE_RATE' => '3', // 合约获利倍率
	'CONTRACT_EXTRACT_LIMIT_RATE' => '0.2', // 合约提取时，只能提取到用户限制资金的蛋提取率
	'CONTRACT_LEVEL_ONE' => '100', // 一级合约蛋数
	'CONTRACT_LEVEL_TWO' => '200', // 二级合约蛋数
	'CONTRACT_LEVEL_THREE' => '1000', // 三级合约蛋数
	'CONTRACT_LEVEL_FOUR' => '2000', // 四级合约蛋数
	'CONTRACT_LEVEL_FIVE' => '4000', // 五级合约蛋数
	'CONTRACT_CYCLE_DAYS' => '6', // 合约周期天数
	'CONTRACT_CYCLE_COMMUNITY_ADD_LIMIT_RATE' => '0.3', // 合约周期社区获取限制率
	'CONTRACT_CYCLE_PROFIT_RATE' => '0.06', // 合约周期获利率
	'CONTRACT_DAILY_EXTRACT_RATE' => '0.06', // 合约每日最多提取已孵化的比例
	'NEST_INVITE_PROFIT_RATE' => '0.06', // 巢给邀请者贡献的获利率
	'NEST_COMMUNITY_B_PROFIT_RATE' => '0.06', // 巢在社区B为上级贡献的获利率
	'NEST_COMMUNITY_C_PROFIT_RATE' => '0.06', // 巢在社区C为上级贡献的获利率
	'USER_WITHDRAW_TAX_RATE' => '0.2', // 用户提现时收取的税率
	'USER_DAILY_CASH_LIMIT' => '100', // 用户日常提现限制
	'USER_TOTAL_WITHDRAWAL_LIMIT' => '1000', // 用户提款上限
	'RECHARGE_APPLICATION_MONEY_MIN' => '100', // 充值最低金额
	'WITHDRAWAL_APPLICATION_MONEY_MIN' => '0', // 提现最低金额
	'TRANSFER_MONEY_MIN' => '100', // 转账最低金额
	'TRANSFER_MONEY_ACTIVE_RATE' => '0.7', // 转账获取活动资金比例
	'TRANSFER_MONEY_LIMIT_RATE' => '0.2', // 转账获取限制资金比例
	'TRANSFER_COINS_RATE' => '0.1', // 转账获取猫币比例
	'COIN_VAL' => '1', // 猫币价值
	'BONUS_ONE_RATE' => '0.13', // 上一级分红金额比例
	'BONUS_TWO_RATE' => '0.03', // 上二级分红金额比例
	'BONUS_THREE_RATE' => '0.02', // 上三级分红金额比例
	'CONTRACT_DAILY_HATCH_RATE' => '0.01', //每日孵化比例
	'CONTRACT_MONEY_ACTIVE_RATE' => '0.7', // 合约获取活动资金比例
	'CONTRACT_MONEY_LIMIT_RATE' => '0.2', // 合约获取限制资金比例
	'CONTRACT_COINS_RATE' => '0.1', // 合约获取猫币比例
	'WITHDRAW_MONEY_LIMIT_RATE' => '0.2', // 提现时转为限制资金的比例
	'WITHDRAW_COINS_RATE' => '0.1', // 提现时转为猫币的比例
	'WITHDRAW_CASH_RATE' => '0.7', // 提现时转为现金的比例
	'WITHDRAW_TODAY_RATE' => '0.06', // 今日提现上限比例
	'WITHDRAWAL_FEE_RATE' => '0.055' // 提现手续费比率
];